# Docker Compose for Development

version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: your_registry/user_authentication:latest
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: mydb_dev
      DATABASE_USER: dev_user
      DATABASE_PASSWORD: dev_password
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  db_data:
