# Docker Compose for Production

version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb_prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: your_registry/user_authentication:latest
    environment:
      DATABASE_HOST: prod_db.example.com
      DATABASE_PORT: 5432
      DATABASE_NAME: mydb_prod
      DATABASE_USER: prod_user
      DATABASE_PASSWORD: prod_password

volumes:
  db_data:
